### PR TITLE
Fix: resolve #148 and improve compatibility with legacy architecture

### LINKED ISSUE #148: ERROR Error: Unsupported top level event type ‘onAdLoaded’ dispatched, js engine: hermes
Hello,
I am trying to integrate MREC ads into my application using the dedicated component, but as soon as I open my application, I get the following error: “ERROR Error: Unsupported top level event type ‘onAdLoaded’ dispatched, js engine: hermes.”

I wanted to investigate the error myself, but when I download and launch the sample project and try to view an MREC, I see a blank screen, as shown in the attached video.

Browsing through the code, I noticed that events for MREC do not seem to be handled. The file that defines the constants for events is completely missinghttps://github.com/appodeal/react-native-appodeal/blob/master/src/RNAppodealEvents.ts

Am I missing something, or are they not implemented correctly?

I'm using react native "react-native": "0.79.5", "react-native-appodeal": "3.8.1" old architecture with hermes.

https://github.com/user-attachments/assets/bbc6d0ae-7440-4c23-92cd-7145e7713627

### PR DESCRIPTION
**Pull request by rolandvar**
This PR includes three commits that resolve the issue reported at https://github.com/appodeal/react-native-appodeal/issues/148 and add improvements for compatibility with React Native's old architecture. The main goal is to prevent initialization crashes and provide robust fallbacks for bridge/view manager usage on legacy setups.

### CODE REVIEW

File: src/RNAppodealEvents.ts [hunk 1]
```diff
@@ -72,3 +72,19 @@ export namespace AppodealRewardedEvents {
   /** Fired when rewarded video ad is clicked */
   export const CLICKED = 'onRewardedVideoClicked';
 }
+
+/**
+ * Mrec ad events
+ */
+export namespace AppodealMrecEvents {
```
Comment (da2gl) [inline src/RNAppodealEvents.ts:79]: Hi, 
We chose not to include `AppodealMrecEvents`, because MREC View, like Banner View, has its own events accessible through the View constructor instead of addEventListener.

Comment (da2gl) [reply src/RNAppodealEvents.ts:79]: Also on iOS we don't support top level events for MREC

**Review by da2gl — APPROVED** [review]
